### ISSUE TITLE
Unable to allocate array with shape and data type

### ISSUE THREAD

**Issue by Becheler** [Becheler/quetzal-CRUMBS#22]
- Quetzal-CRUMBS - Temporal interpolation for missing layers
    ... reading multiband raster sdm_outputs/suitability.tif
        - number of existing bands is 3
        - bands will be macthed against (in years BP): [0, 2000, 7000]
        - number of missing bands is 6998
        - request memory allocation 33.84 GB
    ... creating new array
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/crumbs/interpolate.py", line 145, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.8/dist-packages/crumbs/interpolate.py", line 138, in main
    return temporal_interpolation(
  File "/usr/local/lib/python3.8/dist-packages/crumbs/interpolate.py", line 100, in temporal_interpolation
    new_array = fill_known_bands(ma.zeros(new_shape, dtype=src_array.dtype), src_array, band_to_yearBP)
  File "/usr/local/lib/python3.8/dist-packages/numpy/ma/core.py", line 8154, in __call__
    result = self._func.__call__(*args, **params).view(MaskedArray)
numpy.core._exceptions.MemoryError: Unable to allocate 33.8 GiB for an array with shape (7001, 1024, 1267) and data type float32
```
```

**Comment by Becheler** [comment]
Fixed with Dask and v1.0.15.
